development:
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  database: develop
  username: develop
  password: develop
  host: db
  port: 3306
  
test:
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  database: test
  username: test 
  password: test 
  host: db
  port: 3306

production:
  adapter: mysql2
  reconnect: false
  encoding: utf8mb4
  database: <%= ENV["DB_DB"] %> 
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %> 
  port: 3306
