version: 0.1

environment_variables:
  plaintext:
    CHILD_TEMPLATES: |
      ecs-cluster.yml
      lifecyclehook.yml
      load-balancers.yml
      security-groups.yml
      vpc.yml
    TEMPLATE_FILES: |
      ecs-cluster.yml
      lifecyclehook.yml
      load-balancers.yml
      security-groups.yml
      vpc.yml
    CONFIG_FILES: |
      config-prod.json

phases:
  pre_build:
    commands:
      - echo "Validating CFN templates"
      - |
        for cfn_template in $TEMPLATE_FILES; do
          echo "Validating CloudFormation template file $cfn_template"
          aws cloudformation validate-template --template-body file://infrastructure/$cfn_template
        done
  build:
    commands:
      - echo "Fetching image tag"
      - STACK_NAME=lobsters-app
      - IMAGE_TAG=$(aws ssm get-parameter --names "/$STACK_NAME/image" --query "Parameters[0].Value" --output text)
      - echo "Copying child stack templates to S3"
      - |
        for child_template in $CHILD_TEMPLATES; do
          aws s3 cp "infrastructure/$child_template" "s3://$TEMPLATE_BUCKET/$child_template"
        done
      - aws cloudformation deploy --template-file infrastructure/master.yml --stack-name $STACK_NAME --paramter-overrides TemplatePath=$TEMPLATE_BUCKET ImageTag=$IMAGE_TAG EcrRepo=$ECR_REPO --capabilities CAPABILITY_NAMED_IAM
      # - echo "Updating template configurtion files to use the appropriate values"
      # - |
      #   for conf in $CONFIG_FILES; do
      #     echo "Replacing \"TEMPLATE_PATH_REPLACE_ME\" for \"$TEMPLATE_BUCKET\" in $conf"
      #     sed -i -e "s/TEMPLATE_PATH_REPLACE_ME/$TEMPLATE_BUCKET/" $conf
      #     sed -i -e "s/ECR_REPO_REPLACE_ME/$ECR_REPO/" $conf
      #     sed -i -e "s/IMAGE_TAG_REPLACE_ME/$IMAGE_TAG/" $conf
      #   done
artifacts:
  files:
    - master-stack.yml
    - config-*.json
